# Generated by Django 5.1.7 on 2025-03-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='path/to/default/image.jpg', null=True, upload_to='product_images/'),
        ),
    ]
